[global]
upgrade_only = true

["asciinema/agg"]
asset_filters = ["gnu"]
target = "/usr/local/bin/agg"

["boyter/scc"]
target = "/usr/local/bin/scc"

["chmln/sd"]
asset_filters = ["gnu"]
target = "/usr/local/bin/sd"

["dalance/procs"]
target = "/usr/local/bin/procs"

["denisidoro/navi"]
target = "/usr/local/bin/navi"

["ericchiang/pup"]
target = "/usr/local/bin/pup"

["jesseduffield/lazygit"]
target = "/usr/local/bin/lazygit"

["jhspetersson/fselect"]
target = "/usr/local/bin/fselect"

["jkfran/killport"]
asset_filters = ["x86_64-linux-gnu"]
target = "/usr/local/bin/killport"

["kha7iq/pingme"]
target = "/usr/local/bin/pingme"

["ouch-org/ouch"]
asset_filters = ["gnu"]
target = "/usr/local/bin/ouch"

["pemistahl/grex"]
target = "/usr/local/bin/grex"

["phiresky/ripgrep-all"]
all = true
target = "/usr/local/bin"

["pvolok/mprocs"]
target = "/usr/local/bin/mprocs"

["so-fancy/diff-so-fancy"]
target = "/usr/local/bin/diff-so-fancy"

["TomWright/dasel"]
asset_filters = ["linux_amd64", "gz"]
target = "/usr/local/bin/dasel"

["wagoodman/dive"]
asset_filters = [".tar.gz"]
target = "/usr/local/bin/dive"

["WindSoilder/hors"]
target = "/usr/local/bin/hors"

["wtfutil/wtf"]
asset_filters = ["linux_amd64"]
target = "/usr/local/bin/wtf"

["yudai/gotty"]
asset_filters = ["linux_amd64"]
target = "/usr/local/bin/gotty"
