[global]
upgrade_only = true

["antonmedv/fx"]
target = "/usr/local/bin/fx"

["ariasmn/ugm"]
target = "/usr/local/bin/ugm"

["asciinema/agg"]
target = "/usr/local/bin/agg"
asset_filters = ["gnu"]

["benibela/xidel"]
target = "/usr/local/bin/xidel"

["boyter/scc"]
target = "/usr/local/bin/scc"

["chmln/sd"]
target = "/usr/local/bin/sd"
asset_filters = ["gnu"]

["dalance/procs"]
target = "/usr/local/bin/procs"

["dandavison/delta"]
target = "/usr/local/bin/delta"
asset_filters = ["gnu"]

["F1bonacc1/process-compose"]
target = "/usr/local/bin/process-compose"

["jesseduffield/lazygit"]
target = "/usr/local/bin/lazygit"

["jhspetersson/fselect"]
target = "/usr/local/bin/fselect"

["jkfran/killport"]
target = "/usr/local/bin/killport"
asset_filters = ["x86_64-linux-gnu"]

["joehillen/sysz"]
target = "/usr/local/bin/sysz"

["jorgerojas26/lazysql"]
target = "/usr/local/bin/lazysql"

["Julien-cpsn/ATAC"]
target = "/usr/local/bin/atac"
asset_filters = ["gnu"]

["mikefarah/yq"]
target = "/usr/local/bin/yq"
asset_filters = ["^.tar.gz"]

["mithrandie/csvq"]
target = "/usr/local/bin/csvq"

["mylxsw/redis-tui"]
target = "/usr/local/bin/redis-tui"
asset_filters = ["^arm"]

["nektos/act"]
target = "/usr/local/bin/act"

["ouch-org/ouch"]
target = "/usr/local/bin/ouch"
asset_filters = ["gnu"]

["peltho/tufw"]
target = "/usr/local/bin/tufw"
asset_filters = ["tar.gz"]

["phiresky/ripgrep-all"]
all = true
target = "/usr/local/bin"

["pvolok/mprocs"]
target = "/usr/local/bin/mprocs"

["RustScan/RustScan"]
target = "/usr/local/bin/rustscan"
asset_filters = ["zip"]

["sachaos/viddy"]
target = "/usr/local/bin/viddy"

["sxyazi/yazi"]
target = "/usr/local/bin/yazi"
asset_filters = ["gnu", "zip"]

["tomnomnom/gron"]
target = "/usr/local/bin/gron"

["TomWright/dasel"]
target = "/usr/local/bin/dasel"
asset_filters = ["linux_amd64", "gz"]

["trntv/sshed"]
target = "/usr/local/bin/sshed"
asset_filters = ["tar.gz"]

["wagoodman/dive"]
target = "/usr/local/bin/dive"
asset_filters = [".tar.gz"]

["xo/usql"]
target = "/usr/local/bin/usql"
asset_filters = ["^static"]

["yudai/gotty"]
target = "/usr/local/bin/gotty"
asset_filters = ["linux_amd64"]

["zyedidia/micro"]
target = "/usr/local/bin/micro"
asset_filters = ["tar.gz", "^static", "^sha"]
