[global]
upgrade_only = true

["asciinema/agg"]
target = "/usr/local/bin/agg"
asset_filters = ["gnu"]

["boyter/scc"]
target = "/usr/local/bin/scc"

["chmln/sd"]
target = "/usr/local/bin/sd"
asset_filters = ["gnu"]

["dalance/procs"]
target = "/usr/local/bin/procs"

["dandavison/delta"]
target = "/usr/local/bin/delta"
asset_filters = ["gnu"]

["jesseduffield/lazygit"]
target = "/usr/local/bin/lazygit"

["jhspetersson/fselect"]
target = "/usr/local/bin/fselect"

["jkfran/killport"]
target = "/usr/local/bin/killport"
asset_filters = ["x86_64-linux-gnu"]

["kellyjonbrazil/jc"]
target = "/usr/local/bin/jc"

["kha7iq/pingme"]
target = "/usr/local/bin/pingme"

["ouch-org/ouch"]
target = "/usr/local/bin/ouch"
asset_filters = ["gnu"]

["pemistahl/grex"]
target = "/usr/local/bin/grex"

["phiresky/ripgrep-all"]
all = true
target = "/usr/local/bin"

["pvolok/mprocs"]
target = "/usr/local/bin/mprocs"

["TaKO8Ki/gobang"]
target = "/usr/local/bin/gobang"

["tomnomnom/gron"]
target = "/usr/local/bin/gron"

["TomWright/dasel"]
target = "/usr/local/bin/dasel"
asset_filters = ["linux_amd64", "gz"]

["wagoodman/dive"]
target = "/usr/local/bin/dive"
asset_filters = [".tar.gz"]

["WindSoilder/hors"]
target = "/usr/local/bin/hors"

["xyproto/orbiton"]
target = "/usr/local/bin/o"

["yudai/gotty"]
target = "/usr/local/bin/gotty"
asset_filters = ["linux_amd64"]
