[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank" ]
